---
name: Release Project

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version, must match release candidate version. IMPORTANT - required format
          `X.X.X`, (e.g. `2.0.1`).
        required: true
      date:
        description: Release date stamp, must match release candidate date. IMPORTANT - required format
          `YYYYMMDD`, (e.g. `20240430`).
        required: true
      release_name:
        description: Name of the release to be created. Version in the first place is recommended (e.g.
          `2.0.1-alpha`).
        required: true
      automatic_mode:
        type: boolean
        default: false
        description: Automatically merge PRs, create releases and build images.
      prerelease:
        type: boolean
        default: false
        description: Mark the release as a prerelease.

env:
  RC_BRANCH_NAME: ${{ inputs.version }}-${{ inputs.date }}
  MAIN_BRANCH: ros2

jobs:
  release_repository:
    name: Release repository
    uses: ./.github/workflows/release-repository.yaml
    with:
      release_candidate: ${{ env.RC_BRANCH_NAME }}
      version: ${{ inputs.version }}
      release_name: ${{ inputs.release_name }}
      automatic_mode: ${{ inputs.automatic_mode }}
      prerelease: ${{ inputs.prerelease }}

  build_docker:
    name: Build Docker
    needs: release_repository
    uses: ./.github/workflows/build-docker.yaml
    with:
      build_type: development
    secrets: inherit

  tag_docker_as_stable:
    name: Tag Docker as stable
    needs: build_docker
    uses: ./.github/workflows/build-docker.yaml
    with:
      build_type: stable
      target_distro: humble
      target_release: ${{ inputs.version }}
      target_date: ${{ inputs.date }}

  release_project:
    name: Release project
    runs-on: ubuntu-22.04
    steps:
      - name: Release husarion-ugv-rpi-os-img repository
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: husarion
          repo: husarion-ugv-rpi-os-img
          github_token: ${{ secrets.RAFAL_ACCESS_TOKEN }}
          workflow_file_name: release-repository.yaml
          ref: ${{ env.RC_BRANCH_NAME }}
          client_payload: |
            {
              "release_candidate": "${{ env.RC_BRANCH_NAME }}",
              "version": "${{ inputs.version }}",
              "release_name": "${{ inputs.release_name }}",
              "automatic_mode": "${{ inputs.automatic_mode }}",
              "prerelease": "${{ inputs.prerelease }}"
            }

      - name: Build OS image
        if: ${{ inputs.automatic_mode }}
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: husarion
          repo: husarion-ugv-rpi-os-img
          github_token: ${{ secrets.RAFAL_ACCESS_TOKEN }}
          workflow_file_name: build_and_deploy_image.yaml
          ref: ${{ env.MAIN_BRANCH }}
          client_payload: |
            {
              "dev_image": "false",
              "husarion_ugv_version": "${{ inputs.version }}",
              "image_tag": "${{ inputs.version }}"
            }

      - name: Build flash OS image
        if: ${{ inputs.automatic_mode }}
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: husarion
          repo: husarion-ugv-rpi-os-img
          github_token: ${{ secrets.RAFAL_ACCESS_TOKEN }}
          workflow_file_name: build_and_deploy_flash_os_image.yaml
          ref: ${{ env.MAIN_BRANCH }}
          client_payload: |
            {
              "image_tag": "${{ inputs.version }}"
            }

  docs:
    name: Docs
    runs-on: ubuntu-22.04
    steps:
      - name: Rebuild documentation
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: husarion
          repo: docs_new
          github_token: ${{ secrets.RAFAL_ACCESS_TOKEN }}
          workflow_file_name: build.yml
          ref: master
